### ISSUE TITLE
Compose files need an explicit network definition to avoid IP address issue with VPNs

### ISSUE THREAD

**Issue by 10ofDisks** [eth2-educators/eth2-docker#118]
When a VPN is enabled and you run "sudo docker-compose up -d eth2", you'll see the following error:

`ERROR: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
`

This seems to be a common problem as documented here: https://github.com/docker/for-linux/issues/599

I found a workaround by defining a custom network as part of the compose files, in my case I'm using lh-base.yml, geth.yml, and lh-grafana.yml. I added an entry like the following to those files:

```
networks:
  eth2-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
```
And then for each of the services in those files, adding the following:

```
    networks:
      - eth2-net
```
Now all the services and containers start up fine. Not sure why this works, but sharing this in case you want to incorporate something like this into the code base. With this change, and setting custom ports that map to my VPN's port forwarding options, I've been able to get the services running successfully under VPN.

**Comment by yorickdowne** [comment]
Since this is niche use and my hard-coding a range in the compose files risks "stepping on" a private LAN range, I prefer that users handle this themselves in the `daemon.json` for docker. Arguably, on a machine that uses a VPN, all docker containers should "leave room" for the VPN, not just the ones for this project.

See https://docs.storagemadeeasy.com/appliance/docker_networking for instructions.
